name: flutter_bloc_base
description: Flutter application with Bloc Architecture
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Resource localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2

  cupertino_icons: ^1.0.1
  flutter_bloc: ^6.1.0
  shared_preferences: 0.5.12+4
  sqflite: ^1.3.2+1
  permission_handler: ^5.0.1+1
  connectivity: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Generation resource
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Bold.ttf
        - asset: assets/fonts/Muli-SemiBold.ttf
        - asset: assets/fonts/Muli-Regular.ttf
